title : Goodrichs.NET
tagline: Proving there is such thing as too many kids
author :
  name : Glenn Goodrich 
  email : glenn@goodrichs.net
  github : goodrichs
  twitter : ruprict

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
